---
# actual configuration for samba should be in another module to allow flexibility with other authentication methods

- include_tasks: redhat.yml
  when: samba_enabled and ansible_os_family == "RedHat"

