---
# managa packages and enable service
- name: install samba packages
  package:
    name: "{{ samba_packages }}"
    state: present

- name: Copy custom Samba VFS modules
  copy:
    src: "{{ item }}"
    dest: /usr/lib64/samba/vfs/
    mode: '0644'
  loop: "{{ samba_custom_vfs }}"
  when: samba_custom_vfs is defined and samba_custom_vfs | length > 0

# read all params from ansible, no defaults in the role
- name: Samba config
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0644
  notify: restart_samba

- name: Enable and start winbind
  service:
    name: "{{ samba_winbind_service }}"
    enabled: true
    state: "{{ samba_service_state }}"
  when: samba_manage_winbind

- name: Service enabled and running
  service:
    name: "{{ samba_service }}"
    enabled: true
    state: "{{ samba_service_state }}"
